---
apiVersion: v1
kind: Service
metadata:
  name: wardzinski-resume-service
  namespace: web
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    targetPort: resume-port
  selector:
    name: wardzinski-resume-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  wardzinski-resume-app
  labels:
    name:  wardzinski-resume-app
  namespace: web
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      name: wardzinski-resume-app
  template:
    metadata:
      labels:
        name:  wardzinski-resume-app
    spec:
      containers:
      - image: toddwardzinski/wardzinskiresume:latest
        name: wardzinski-resume-app
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
        livenessProbe:
          httpGet:
            path: /index.html
            port: 80
          initialDelaySeconds: 90
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /index.html
            port: 80  
          initialDelaySeconds: 30
          timeoutSeconds: 10   
        ports:
        - containerPort: 80
          name: resume-port
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred