apiVersion: v1
data:
  config.yaml: |
    # Name of the tunnel you want to run
    tunnel: wardzinski-info-tunnel
    credentials-file: /etc/cloudflared/creds/credentials.json
    # Serves the metrics server under /metrics and the readiness server under /ready
    metrics: 0.0.0.0:2000
    # Autoupdates applied in a k8s pod will be lost when the pod is removed or restarted, so
    # autoupdate doesn't make sense in Kubernetes. However, outside of Kubernetes, we strongly
    # recommend using autoupdate.
    no-autoupdate: true
    # The `ingress` block tells cloudflared which local service to route incoming
    # requests to. For more about ingress rules, see
    # https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/ingress
    #
    # Remember, these rules route traffic from cloudflared to a local service. To route traffic
    # from the internet to cloudflared, run `cloudflared tunnel route dns <tunnel> <hostname>`.
    # E.g. `cloudflared tunnel route dns example-tunnel tunnel.example.com`.
    ingress:
    # The first rule proxies traffic to the httpbin sample Service defined in app.yaml
    #- hostname: tunnel.wardzinski.info
    #  service: http://web-service
    # This rule sends traffic to the built-in hello-world HTTP server. This can help debug connectivity
    # issues. If hello.example.com resolves and tunnel.example.com does not, then the problem is
    # in the connection from cloudflared to your local service, not from the internet to cloudflared.
    - hostname: www.wardzinski.info
      service: http://wardzinskiresumesvc:80
    # This rule matches any traffic which didn't match a previous rule, and responds with HTTP 404.
    - service: http_status:404
kind: ConfigMap
metadata:
  name: cloudflared
  namespace: wardzinskiresume
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: wardzinskiresume
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloudflared
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
      - args:
        - tunnel
        - --config
        - /etc/cloudflared/config/config.yaml
        - run
        image: cloudflare/cloudflared:2023.8.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 1
          httpGet:
            path: /ready
            port: 2000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: cloudflared
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/cloudflared/config
          name: config
          readOnly: true
        - mountPath: /etc/cloudflared/creds
          name: creds
          readOnly: true
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: creds
        secret:
          defaultMode: 420
          secretName: tunnel-credentials
      - configMap:
          defaultMode: 420
          items:
          - key: config.yaml
            path: config.yaml
          name: cloudflared
        name: config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  wardzinski-resume-app
  labels:
    name:  wardzinski-resume-app
  namespace: wardzinskiresume
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      name: wardzinski-resume-app
  template:
    metadata:
      labels:
        name:  wardzinski-resume-app
    spec:
      containers:
      - image: toddwardzinski/resume:latest
        name: wardzinski-resume-app
        resources: {}
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /index.html
            port: 80
          initialDelaySeconds: 15
          timeoutSeconds: 25
        readinessProbe:
          httpGet:
            path: /index.html
            port: 80  
          initialDelaySeconds: 15
          timeoutSeconds: 25
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: wardzinski-resume-app
  name: wardzinskiresumesvc
  namespace: wardzinskiresume
spec:
  internalTrafficPolicy: Cluster
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    name: wardzinski-resume-app
  type: ClusterIP