---
- name: Playbook To Do Shit
  hosts: localhost
  tasks:
    - name: Create a k8s namespace
      community.kubernetes.k8s:
        name: testing
        api_version: v1
        kind: Namespace
        state: present