apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wardinfo-ingress
  namespace: wardzinskiinfo
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - wardzinski.info
    - www.wardzinski.info
    secretName: echo-tls
  rules:
  - host: www.wardzinski.info
    http:
      paths:
      - backend:
          serviceName: wardzinskiinfosvc
          servicePort: 80
  - host: wardzinski.info
    http:
      paths:
      - backend:
          serviceName: wardzinskiinfosvc
          servicePort: 80


