# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: wardinfo-ingress
#   namespace: wardzinskiresume
# spec:
#   rules:
#   - host: www.wardzinski.info
#     http:
#       paths:
#       - backend:
#           serviceName: wardzinskiinfosvc
#           servicePort: 80
#   - host: wardzinski.info
#     http:
#       paths:
#       - backend:
#           serviceName: wardzinskiinfosvc
#           servicePort: 80
# ---
# https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wardzinskiinfo-ingress
  namespace: wardzinskiresume
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: www.wardzinski.info
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wardzinskiinfosvc
            port:
              number: 80
  - host: wardzinski.info
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wardzinskiinfosvc
            port:
              number: 80
